# Generated by Django 4.2.29 on 2026-04-07 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=100)),
                ('seniority', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=10)),
                ('annual_min', models.IntegerField(blank=True, null=True)),
                ('annual_max', models.IntegerField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'salary_history',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_input', models.TextField()),
                ('region', models.CharField(default='TN', max_length=10)),
                ('a2a_payload', models.JSONField(blank=True, null=True)),
                ('full_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='SalaryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=100)),
                ('seniority', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('annual_min', models.IntegerField()),
                ('annual_max', models.IntegerField()),
                ('hourly_min', models.IntegerField(blank=True, null=True)),
                ('hourly_max', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'salary_rates',
                'unique_together': {('role_title', 'seniority', 'region')},
            },
        ),
    ]
