# Generated by Django 4.2.29 on 2026-04-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_user_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
