# Generated by Django 4.2.29 on 2026-04-07 17:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_sent_to_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offer_made', 'Offer Made'), ('accepted', 'Accepted Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Candidate Withdrew')], default='invited', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('offer_date', models.DateTimeField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('hr_notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_invitations', to='api.candidate')),
            ],
            options={
                'db_table': 'job_invitations',
                'ordering': ['-invited_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('seniority', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_skills', models.JSONField(default=list)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('closed', 'Closed'), ('on_hold', 'On Hold')], default='open', max_length=20)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_positions', to='api.candidate')),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='api.hruser')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='api.usersession')),
            ],
            options={
                'db_table': 'job_postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('candidate_interested', 'Candidate Interested'), ('no_response', 'No Response'), ('interview_reminder', 'Interview Reminder'), ('offer_pending', 'Offer Pending'), ('position_filled', 'Position Filled'), ('deadline_approaching', 'Deadline Approaching')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.hruser')),
                ('job_invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jobinvitation')),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jobposting')),
            ],
            options={
                'db_table': 'recruitment_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobinvitation',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.jobposting'),
        ),
        migrations.AddField(
            model_name='jobinvitation',
            name='notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_invitation', to='api.candidatenotification'),
        ),
        migrations.AlterUniqueTogether(
            name='jobinvitation',
            unique_together={('job_posting', 'candidate')},
        ),
    ]
