# Generated by Django 4.2.29 on 2026-04-08 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_jobinvitation_jobposting_recruitmentnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateJobMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField()),
                ('skill_match_score', models.FloatField()),
                ('seniority_match_score', models.FloatField()),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed by HR'), ('contacted', 'Candidate Contacted'), ('rejected', 'Not a Fit'), ('hired', 'Hired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='api.candidate')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_matches', to='api.jobposting')),
            ],
            options={
                'db_table': 'candidate_job_matches',
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('candidate', 'job_posting')},
            },
        ),
    ]
