# Generated by Django 4.2.29 on 2026-04-13 07:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_candidate_job_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLifecycleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_events', to='api.hruser')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='api.jobposting')),
            ],
            options={
                'db_table': 'job_lifecycle_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['job_posting', '-timestamp'], name='job_lifecyc_job_pos_9d9456_idx'), models.Index(fields=['hr_user', '-timestamp'], name='job_lifecyc_hr_user_cb28e6_idx'), models.Index(fields=['event_type', '-timestamp'], name='job_lifecyc_event_t_1f891c_idx')],
            },
        ),
    ]
