"""
ESG Scorer agent — produces structured ESG scores and the final report.

Takes all previous agent outputs and synthesizes a comprehensive assessment.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_groq import ChatGroq

from green_analysis.agents.state import EnvironmentalState, ESGScore

logger = logging.getLogger(__name__)


def _build_final_report(state: EnvironmentalState, esg: ESGScore) -> str:
    """Compile all agent outputs into a markdown final report."""
    parsed = state.parsed_input
    impact = state.impact_assessment

    lines = [
        "# Environmental Analysis & Green Recommendations Report",
        "",
        "---",
        "",
        "## 1. Business Overview",
        "",
    ]

    if parsed:
        lines += [
            f"- **Description:** {parsed.business_description}",
            f"- **Sector:** {parsed.industry_sector} / {parsed.sub_sector}",
            f"- **Location:** {parsed.location}",
            f"- **Scale:** {parsed.scale}",
            f"- **Activities:** {', '.join(parsed.activities)}",
            f"- **Resources:** {', '.join(parsed.resources_used)}",
            f"- **EU Export:** {'Yes' if parsed.exports_to_eu else 'No'}",
            "",
        ]

    lines += ["## 2. Environmental Impact Assessment", ""]

    if impact:
        lines += [
            f"- **Carbon Footprint:** {impact.carbon_estimate_range}",
            f"- **Energy Intensity:** {impact.energy_intensity}",
            f"- **Water Usage:** {impact.water_usage_category}"
            + (f" (~{impact.water_usage_m3_per_year:,.0f} m³/year)" if impact.water_usage_m3_per_year else ""),
            f"- **Waste Profile:** {', '.join(impact.waste_profile)}",
            f"- **Waste Volume:** {impact.waste_volume_category}",
            "",
            "### Key Environmental Risks",
            "",
        ]
        for risk in impact.key_environmental_risks:
            lines.append(f"- {risk}")
        lines += ["", f"*Methodology: {impact.methodology_notes}*", ""]

    lines += ["## 3. Recommended Green Certifications", ""]

    if state.certifications:
        for i, cert in enumerate(state.certifications, 1):
            lines += [
                f"### {i}. {cert.name} ({cert.priority} priority)",
                f"- **Issuing body:** {cert.issuing_body}",
                f"- **Relevance:** {cert.relevance}",
                f"- **Cost:** {cert.estimated_cost}",
                f"- **Timeline:** {cert.estimated_timeline}",
                f"- **Strategic value:** {cert.strategic_value}",
                "",
            ]
    else:
        lines.append("*No certifications recommended.*\n")

    lines += ["## 4. Sustainability Recommendations", ""]

    if state.recommendations:
        for i, rec in enumerate(state.recommendations, 1):
            programs = ", ".join(rec.relevant_programs) if rec.relevant_programs else "None"
            lines += [
                f"### {i}. {rec.title} [{rec.category}]",
                f"- **Impact:** {rec.estimated_impact} | **Difficulty:** {rec.implementation_difficulty} | **Cost:** {rec.estimated_cost}",
                f"- {rec.description}",
                f"- **Tunisia context:** {rec.tunisia_context}",
                f"- **Funding programs:** {programs}",
                "",
            ]
    else:
        lines.append("*No recommendations generated.*\n")

    lines += [
        "## 5. ESG Score",
        "",
        f"| Pillar | Score | Weight |",
        f"|--------|-------|--------|",
        f"| Environmental | {esg.environmental_score:.0f}/100 | 50% |",
        f"| Social | {esg.social_score:.0f}/100 | 25% |",
        f"| Governance | {esg.governance_score:.0f}/100 | 25% |",
        f"| **Composite** | **{esg.composite_score:.0f}/100** | **Grade: {esg.letter_grade}** |",
        "",
        f"### Summary",
        "",
        esg.summary,
        "",
        "---",
        "",
        "*Generated by the Intelligent Environmental Analysis & Green Recommendations Module*",
    ]

    return "\n".join(lines)


def run_esg_scorer(
    state: EnvironmentalState,
    llm: ChatGroq,
    system_prompt: str,
) -> dict[str, Any]:
    """Score the business on ESG criteria and compile the final report."""

    parsed = state.parsed_input
    impact = state.impact_assessment

    # Build context from all previous agents
    context_parts = []

    if parsed:
        context_parts.append(
            f"**Business:** {parsed.business_description}\n"
            f"Sector: {parsed.industry_sector}, Location: {parsed.location}, "
            f"Scale: {parsed.scale}, EU Export: {parsed.exports_to_eu}"
        )

    if impact:
        context_parts.append(
            f"**Impact Assessment:**\n"
            f"Carbon: {impact.carbon_estimate_range}\n"
            f"Energy intensity: {impact.energy_intensity}\n"
            f"Water usage: {impact.water_usage_category}\n"
            f"Waste: {', '.join(impact.waste_profile)}\n"
            f"Risks: {', '.join(impact.key_environmental_risks)}"
        )

    if state.certifications:
        cert_list = ", ".join(
            f"{c.name} ({c.priority})" for c in state.certifications
        )
        context_parts.append(f"**Recommended Certifications:** {cert_list}")

    if state.recommendations:
        rec_list = "\n".join(
            f"- {r.title} [{r.category}] (impact: {r.estimated_impact})"
            for r in state.recommendations
        )
        context_parts.append(f"**Sustainability Recommendations:**\n{rec_list}")

    full_context = "\n\n".join(context_parts)

    user_message = (
        f"Évaluez cette entreprise selon les critères ESG sur la base de l'analyse complète ci-dessous :\n\n"
        f"{full_context}\n\n"
        f"Retournez un objet JSON correspondant au schéma ESGScore avec : "
        f"environmental_score, social_score, governance_score, composite_score, "
        f"letter_grade, environmental_breakdown, social_breakdown, "
        f"governance_breakdown, summary.\n"
        f"Retournez UNIQUEMENT du JSON valide, sans balises markdown."
    )

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_message),
    ]

    try:
        response = llm.invoke(messages)
        content = response.content.strip()

        if content.startswith("```"):
            content = content.split("\n", 1)[1] if "\n" in content else content[3:]
        if content.endswith("```"):
            content = content[:-3]
        content = content.strip()

        esg = ESGScore.model_validate_json(content)

        # Compile the final report
        report = _build_final_report(state, esg)

        trace_steps = [
            {"step": "llm_call", "detail": "Synthesizing ESG scores from all agent outputs"},
            {"step": "result", "detail": f"E: {esg.environmental_score:.0f}, S: {esg.social_score:.0f}, G: {esg.governance_score:.0f} → {esg.letter_grade} ({esg.composite_score:.0f}/100)"},
            {"step": "report", "detail": f"Generated final report ({len(report)} chars)"},
        ]

        return {
            "esg_score": esg,
            "final_report": report,
            "current_agent": ["esg_scorer"],
            "_trace": {"esg_scorer": trace_steps},
        }

    except (json.JSONDecodeError, Exception) as exc:
        logger.error("ESG scorer failed: %s", exc)
        return {
            "current_agent": ["esg_scorer"],
            "errors": [f"ESG scorer error: {exc}"],
            "_trace": {"esg_scorer": [{"step": "error", "detail": str(exc)}]},
        }
