# Generated by Django 6.0.2 on 2026-03-27 00:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('clarification_needed', 'Clarification Needed'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=25)),
                ('raw_input', models.TextField(help_text='Free-text business description')),
                ('follow_up_questions', models.JSONField(blank=True, default=list)),
                ('user_responses', models.JSONField(blank=True, default=dict)),
                ('parsed_input', models.JSONField(blank=True, null=True)),
                ('impact_assessment', models.JSONField(blank=True, null=True)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('esg_score', models.JSONField(blank=True, null=True)),
                ('final_report', models.TextField(blank=True, default='')),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
