# Generated by Django 6.0.2 on 2026-03-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='agent_status',
            field=models.JSONField(blank=True, default=dict, help_text='Per-agent status: {"input_parser": "completed", "impact_analyst": "running", ...}'),
        ),
    ]
