# Generated by Django 6.0.2 on 2026-03-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_analysis', '0002_analysissession_agent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='agent_trace',
            field=models.JSONField(blank=True, default=dict, help_text='Per-agent reasoning steps: {"input_parser": [{"step": "...", "detail": "..."}], ...}'),
        ),
    ]
