# Generated by Django 6.0.2 on 2026-04-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_analysis', '0003_analysissession_agent_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='critique_history',
            field=models.JSONField(blank=True, default=list, help_text='Episodic memory: list of critique dicts from the Reflexion critic agent'),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='reflexion_count',
            field=models.IntegerField(default=0, help_text='Number of reflexion iterations executed'),
        ),
    ]
