# Generated by Django 6.0.4 on 2026-04-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_analysis', '0004_analysissession_critique_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissession',
            name='critique_history',
        ),
        migrations.RemoveField(
            model_name='analysissession',
            name='reflexion_count',
        ),
    ]
